### ISSUE TITLE
New urls

### ISSUE THREAD

**Issue by vincent-inviseo** [lowatt/lowatt-enedis#55]
Do you know exposed urls will change soon ?

![Capture d’écran du 2024-03-06 15-29-53](https://github.com/lowatt/lowatt-enedis/assets/132346203/6bf794f8-6bb2-43f3-a099-fb235c19e708)

**Comment by vincent-inviseo** [comment]
Okay, I didn't have this information when I wrote the issue. Thanks

**Comment by vincent-inviseo** [comment]
Hello do you know the date about enedis urls migration ?

**Comment by jbjuin** [comment]
Hi, just received that email:
![image](https://github.com/user-attachments/assets/d07b19d4-eebf-4c4a-93ef-f042224d6149)

Seems that the date is 23 of september, in 10 days.

**Comment by vincent-agi** [comment]
Hi i will propose a PR at the end of day

**Comment by philpep** [comment]
When trying to use new urls I get: ```urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'sge-ws.enedis.fr'.```. Wonder if we need new client certificates or if it's a bug on enedis side.

**Comment by jbjuin** [comment]
Hi, the link in the last email is broken for me ? Were you able to get the new certificates ?

**Comment by vincent-inviseo** [comment]
Hi we must download new certificates front enedis ?
But actually i use domain SSL like GEOTRUST that i pass as params to request to get data from enedis sge

**Comment by jbjuin** [comment]
> Hi we must download new certificates front enedis ? But actually i use domain SSL like GEOTRUST that i pass as params to request to get data from enedis sge

Yes same here, I never get why we have to get some certificates from them since we don't use them at the end. We just call the API with the certificates we got from Gandi.

**Comment by jbjuin** [comment]
> > Hi, the link in the last email is broken for me. Were you able to get the new certificates ?
> 
> I was able to get the new certificates but the link is now broken for me as well. If you need them, I guess you can ask holomogation [at] enedis.fr or contrat-tiers [at] enedis.fr for a new link.
> 
> **Edit:** They just sent a new email with a new link to download the certificates.
> 
> > Yes same here, I never get why we have to get some certificates from them since we don't use them at the end. We just call the API with the certificates we got from Gandi.
> 
> I'm not an expert in TLS certificates but from what I understand: The certificate you created and sent to Enedis is used by them to make sure the requests they receive is from you. It's the opposite for the certificate created by Enedis and send to us. We can use it to make sure we are communicating with Enedis' servers and not an imposter, but it depends on the software stack you are using to make requests and it may require specific configuration or coding.

Yes that was my understanding as well, they may be used in some specific configurations. I filled a ticket on SPICE and I just received a new email (slightly different wording than the previous one) with a functional link.

Thanks anyway for your reply !

**Comment by philpep** [comment]
I think enedis server was sending the wrong server certificates few days ago but seems it's fixed now.

There's no impact on lowatt-enedis since we use certifi (mozilla root certificates) which includes Geotrust.
